apiVersion: v1
kind: Service
metadata:
  name: code-compiler-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: code-compiler
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
