apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-compiler
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-compiler
  template:
    metadata:
      labels:
        app: code-compiler
    spec:
      containers:
        - name: code-compiler
          image: aryan211345/code-compiler:v7
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "v7"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
